# Generated by Django 3.2.1 on 2023-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_description', models.CharField(max_length=255)),
                ('subject_icon', models.CharField(max_length=100)),
            ],
        ),
    ]
