# Generated by Django 3.2.1 on 2023-12-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_bank', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
